# Site settings
title: COVID-19 Inform
description: COVID-19 Information Portal
baseurl: "/home" 
url: "https://covid19inform.github.io" 

# User settings
username: COVID-19 Inform
user_title: COVID-19 Information Portal

exclude: ['package.json', 'src' , 'node_modules']
